import { LeadStatus } from "@prisma/client";
import { StatusMetadata } from "../types/metadata";

export function getLeadStatusMetadata(status: LeadStatus): StatusMetadata {
  const metadata: Record<LeadStatus, StatusMetadata> = {
    [LeadStatus.NEW]: {
      label: "New",
      color: "bg-zinc-500/10 text-zinc-500 border-zinc-500/20",
      icon: "Inbox",
      description: "Newly captured lead",
      order: 1,
      variant: "outline",
    },
    [LeadStatus.CONTACTED]: {
      label: "Contacted",
      color: "bg-blue-500/10 text-blue-500 border-blue-500/20",
      icon: "Phone",
      description: "Initial contact made",
      order: 2,
      variant: "outline",
    },
    [LeadStatus.NO_RESPONSE]: {
      label: "No Response",
      color: "bg-gray-500/10 text-gray-500 border-gray-500/20",
      icon: "Clock",
      description: "No response from lead",
      order: 3,
      variant: "outline",
    },
    [LeadStatus.REPLIED]: {
      label: "Replied",
      color: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20",
      icon: "MessageCircle",
      description: "Lead replied to contact",
      order: 4,
      variant: "outline",
    },
    [LeadStatus.INTERESTED]: {
      label: "Interested",
      color: "bg-sky-500/10 text-sky-500 border-sky-500/20",
      icon: "ThumbsUp",
      description: "Lead showed interest",
      order: 5,
      variant: "outline",
    },
    [LeadStatus.QUALIFIED]: {
      label: "Qualified",
      color: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
      icon: "CheckCircle2",
      description: "Lead is qualified",
      order: 6,
      variant: "outline",
    },
    [LeadStatus.DISCOVERY]: {
      label: "Discovery",
      color: "bg-violet-500/10 text-violet-500 border-violet-500/20",
      icon: "Search",
      description: "Requirement discovery call",
      order: 7,
      variant: "outline",
    },
    [LeadStatus.PROPOSAL]: {
      label: "Proposal",
      color: "bg-purple-500/10 text-purple-500 border-purple-500/20",
      icon: "FileText",
      description: "Proposal sent",
      order: 8,
      variant: "outline",
    },
    [LeadStatus.NEGOTIATION]: {
      label: "Negotiation",
      color: "bg-orange-500/10 text-orange-500 border-orange-500/20",
      icon: "MessageSquare",
      description: "Negotiating terms",
      order: 9,
      variant: "outline",
    },
    [LeadStatus.WON]: {
      label: "Won",
      color: "bg-green-500/10 text-green-500 border-green-500/20",
      icon: "Trophy",
      description: "Deal won",
      order: 10,
      variant: "outline",
    },
    [LeadStatus.CLIENT]: {
      label: "Client",
      color: "bg-teal-500/10 text-teal-500 border-teal-500/20",
      icon: "UserCheck",
      description: "Converted to client",
      order: 11,
      variant: "outline",
    },
    [LeadStatus.LOST]: {
      label: "Lost",
      color: "bg-rose-500/10 text-rose-500 border-rose-500/20",
      icon: "XCircle",
      description: "Lead was lost",
      order: 12,
      variant: "outline",
    },
    [LeadStatus.NOT_INTERESTED]: {
      label: "Not Interested",
      color: "bg-red-500/10 text-red-500 border-red-500/20",
      icon: "XOctagon",
      description: "Lead not interested",
      order: 13,
      variant: "outline",
    },
    [LeadStatus.FOLLOW_UP_LATER]: {
      label: "Follow-up Later",
      color: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
      icon: "CalendarClock",
      description: "Follow up required later",
      order: 14,
      variant: "outline",
    },
  };

  return metadata[status];
}
