import React from "react";
import { DocumentData, DocumentType, CompanySettings, PaymentSettings } from "./types";
import { DocumentHeader } from "./DocumentHeader";
import { ClientProjectBlock } from "./ClientProjectBlock";
import { ServicesTable } from "./ServicesTable";
import { SummaryBlock } from "./SummaryBlock";
import { DeliverablesChecklist } from "./DeliverablesChecklist";
import { PaymentBlock } from "./PaymentBlock";
import { TermsBlock } from "./TermsBlock";
import { DocumentFooter } from "./DocumentFooter";

interface DocumentEngineProps {
  type: DocumentType;
  data: DocumentData;
  companyInfo: CompanySettings;
  paymentInfo?: PaymentSettings;
}

export const DocumentEngine: React.FC<DocumentEngineProps> = ({
  type,
  data,
  companyInfo,
  paymentInfo,
}) => {
  return (
    <div 
      className="bg-white w-[210mm] min-h-[297mm] mx-auto relative shadow-2xl flex flex-col font-montserrat"
      style={{
        // A4 Paper proportions for preview purposes, exact A4 size enforced when printing
        width: "210mm",
        minHeight: "297mm",
        color: "#111111", // Primary Black
      }}
    >
      <DocumentHeader type={type} data={data} companyInfo={companyInfo} />

      <main className="flex-1 px-[15mm] py-[10mm] flex flex-col gap-8">
        <ClientProjectBlock type={type} data={data} companyInfo={companyInfo} />
        
        {type !== "RECEIPT" && (
          <ServicesTable items={data.items} />
        )}

        {type === "RECEIPT" && (
          <div className="text-red-500 font-bold p-4 border border-red-500">
            [Receipt Payment Details Table to be implemented]
          </div>
        )}

        <div className="flex flex-row justify-between items-start gap-8">
          <div className="flex-1 w-full">
            {type === "QUOTATION" && data.deliverables && data.deliverables.length > 0 && (
              <DeliverablesChecklist deliverables={data.deliverables} />
            )}
            {type === "INVOICE" && paymentInfo && (
              <PaymentBlock paymentInfo={paymentInfo} />
            )}
          </div>
          
          <div className="w-1/2 shrink-0">
             <SummaryBlock data={data} />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mt-auto">
           {type !== "RECEIPT" && <TermsBlock />}
           <div className="col-start-2">
             <div className="border border-[#E6E6E6] rounded-xl p-5 h-full bg-[#F8F8F8]">
               <h4 className="font-semibold text-sm mb-4">ACCEPTANCE / AUTHENTICATION</h4>
               <p className="text-xs font-bold text-[#C1121F] mb-1">DIGITALLY GENERATED DOCUMENT</p>
               <p className="text-xs text-gray-500 mb-6">Generated by Random Frames OS.<br/>No physical signature required.</p>
               
               <p className="font-bold text-sm text-[#C1121F]">THANK YOU!</p>
               <p className="text-xs mt-1">Thank you for considering Random Frames. We look forward to working with you.</p>
             </div>
           </div>
        </div>
      </main>

      <DocumentFooter companyInfo={companyInfo} />
    </div>
  );
};
