import { WorkflowEvent } from "../events";
import { EventBus } from "../event-bus";
import { logActivity } from "@/lib/timeline";
import { prisma } from "@/lib/prisma";
import { Logger } from "@/lib/logger";

export function registerTimelineHandlers() {
  // --- CRM & Lead Timeline Events ---
  EventBus.subscribe(WorkflowEvent.LEAD_CREATED, 'Timeline_LeadCreated', async (payload) => {
    const lead = await prisma.lead.findUnique({ where: { id: payload.leadId } });
    await logActivity({
      type: "SYSTEM",
      description: lead ? `Lead '${lead.businessName || lead.id}' was created and assigned to Operations` : "New lead created and assigned to Operations",
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.LEAD_CONVERTED, 'Timeline_LeadConverted', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Lead successfully converted to client profile`,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.CLIENT_CREATED, 'Timeline_ClientCreated', async (payload) => {
    const client = await prisma.client.findUnique({ where: { id: payload.clientId } });
    if (!client) return;
    await logActivity({
      type: "SYSTEM",
      description: `Client '${client.businessName}' was onboarded`,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  // --- Project & Shoot Timeline Events ---
  EventBus.subscribe(WorkflowEvent.PROJECT_CREATED, 'Timeline_ProjectCreated', async (payload) => {
    const project = await prisma.project.findUnique({ where: { id: payload.projectId } });
    if (!project) return;
    await logActivity({
      type: "SYSTEM",
      description: `Project '${project.title}' was created (Creative Owner: Founder, Ops Owner: Co-Founder)`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.PROJECT_UPDATED, 'Timeline_ProjectUpdated', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Project milestone and schedule were updated`,
      projectId: payload.projectId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.SHOOT_SCHEDULED, 'Timeline_ShootScheduled', async (payload) => {
    const shoot = await prisma.shoot.findUnique({ where: { id: payload.shootId } });
    if (!shoot) return;
    await logActivity({
      type: "SYSTEM",
      description: `Shoot '${shoot.title}' was scheduled (Creative Owner: Founder)`,
      shootId: payload.shootId,
      projectId: payload.projectId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.SHOOT_COMPLETED, 'Timeline_ShootCompleted', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Shoot production was marked completed`,
      shootId: payload.shootId,
      projectId: payload.projectId,
      metadata: payload
    });
  });

  // --- Content & Delivery Timeline Events ---
  EventBus.subscribe(WorkflowEvent.DELIVERABLE_CREATED, 'Timeline_DeliverableCreated', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Media deliverable uploaded to content pipeline for review`,
      shootId: payload.shootId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.DELIVERY_COMPLETED, 'Timeline_DeliveryCompleted', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Client delivery bundle confirmed completed and approved`,
      projectId: payload.projectId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.FOLDER_CREATED, 'Timeline_FolderCreated', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Google Drive folder structure created automatically`,
      projectId: payload.entityType === 'Project' ? payload.entityId : undefined,
      clientId: payload.entityType === 'Client' ? payload.entityId : undefined,
      shootId: payload.entityType === 'Shoot' ? payload.entityId : undefined,
      metadata: payload
    });
  });

  // --- Finance Timeline Events ---
  EventBus.subscribe(WorkflowEvent.QUOTATION_CREATED, 'Timeline_QuotationCreated', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Quotation was drafted and shared with pipeline`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.QUOTATION_APPROVED, 'Timeline_QuotationApproved', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Quotation was formally approved by client`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.INVOICE_CREATED, 'Timeline_InvoiceCreated', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Invoice generated by Finance team`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.INVOICE_SENT, 'Timeline_InvoiceSent', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Invoice transmitted to client relationship owner`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.INVOICE_PAID, 'Timeline_InvoicePaid', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Invoice marked paid and reconciled in ledger`,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.PAYMENT_RECEIVED, 'Timeline_PaymentReceived', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Payment of ${payload.amount} received into bank account`,
      metadata: payload
    });
  });

  EventBus.subscribe(WorkflowEvent.EXPENSE_LOGGED, 'Timeline_ExpenseLogged', async (payload) => {
    await logActivity({
      type: "SYSTEM",
      description: `Expense of ${payload.amount} logged against operations`,
      projectId: payload.projectId,
      clientId: payload.clientId,
      metadata: payload
    });
  });
}
